### ISSUE TITLE
Config for new master version

### ISSUE THREAD

**Issue by DL2MF** [dl9rdz/rdz_ttgo_sonde#1]
Hi Hans-Peter,

really a great and very nice project, congrats! 

I adapted your latest dev branch to my TTGO ESP32 LoRa V2.1 board (uses port 21/22 for the OLED). Maybe we can make some config additions for several boards in your new config.
Can you please upload the latest config to the data directory.

73 Meinhard "Mike", DL2MF

**Comment by DL2MF** [comment]
OK, found in todays devel-branch under construction ;-)

**Comment by dl9rdz** [comment]
Started some code reorg today to make this configuration configurable. Not yet finished, and I will be away on holidays for the next days, so progress will take some time... But I also ordered a v2.1 board from China two weeks back (which should arrive here next week), so I will also be able to test the code with that board.

**Comment by sp3rat** [comment]
Hi Hans-Peter,
I am sorry my English.
I like your project rdz_ttgo_sonde.
I have one question. How to setup my IP as static?
Because  the ttgo many times do not working with my wifi network.
73! Jurek, de sp3rat

**Comment by dl9rdz** [comment]
Currently in Station Mode IP is always dynamic. Change probable possible in source code, will put this on my todo list
In AP mode IP is always 192.168.4.1

Network is always fine with my Android AP but needs several tries with my Fritzbox AP. Will have a look how to improve this when back in Passau next week

**Comment by dl9rdz** [comment]
WiFi networking should now be stable (I hope), closing this issue.
If there is a real need for static IP addresses in station mode let me know.
