### ISSUE TITLE
map function does not work

### ISSUE THREAD

**Issue by 14ri004** [dl9rdz/rdz_ttgo_sonde#105]
![Screenshot_20210724-144050_Chrome](https://user-images.githubusercontent.com/87615097/126871075-450e311f-c961-4754-8328-4f4ae1ef4923.jpg)

**Comment by LukePrior** [comment]
This has already been addressed with #102

**Comment by 14ri004** [comment]
hello, i read this post but how to fix this problem ???? not well understood what to do
