### ISSUE TITLE
Data should only show active QRG's

### ISSUE THREAD

**Issue by zanco** [dl9rdz/rdz_ttgo_sonde#12]
Hi,
with only 10 QRG's active in the QRG list the RDZSonde Server shows 19 QRG's in the Data tab.

Only number 20 with no name and no "Active" mark does not appear over there.

Could the "Data" tab be limited to the active QRG's ?

Thanks,

Ben - PE2BZ

(running version devel20190911 )

**Comment by dl9rdz** [comment]
Data tab now shows only active frequencies
