### ISSUE TITLE
sonde RS92

### ISSUE THREAD

**Issue by 14ri004** [dl9rdz/rdz_ttgo_sonde#138]
hi, on the Livemap the RS92 probe is not listed and is not visible, so what is in the list of the TTGO scan,

![LIVEMAP](https://user-images.githubusercontent.com/87615097/129717685-0d61e2c7-b01e-4f80-a584-47915c60da43.JPG)

![livemap2](https://user-images.githubusercontent.com/87615097/129717789-7571bb13-61a1-4f6d-b697-30a8ffb1b419.JPG)

**Comment by dl9rdz** [comment]
Thanks for the observation.

That is a combination of two artefacts: The RS92 decoder always sets validID to true, even if no frame was decoded (lat and lon is 0 in that case), and in that case the live map does not update the page content (if validID is true but lat or lon is 0). As soon as an RS92 is decoded, the display on the live map should be correct.

**Comment by 14ri004** [comment]
Thanks for the reply, it amazed me not to see the RS92 show in the livemap scan, like the M10 / RS41, okay i will test asap if it shows up, thanks
