### ISSUE TITLE
livemap

### ISSUE THREAD

**Issue by 14ri004** [dl9rdz/rdz_ttgo_sonde#142]
**Describe the bug**
hello, yesterday I had a little problem with the livemap, see photos

version devel20210817

![sonde etrange](https://user-images.githubusercontent.com/87615097/131480173-48fa6e98-37c0-43dc-b444-57328b0729aa.JPG)

![sonde etrange2](https://user-images.githubusercontent.com/87615097/131480196-2412d76c-ecb1-4094-b2e7-4fc3dab46fb4.JPG)

**Comment by LukePrior** [comment]
I have a feeling that this has to do with latitude being provided incorrectly, I haven't checked the code but if it's not in the range -90 to 90 you may see things like that.

**Comment by 14ri004** [comment]
hello, sorry for yesterday, I took the wrong forum, this is the first time he has indicated this to me, he goes around the world to mark the landing point just next to the probe, very strange as an indication , a little bug probably, thank you

**Comment by LukePrior** [comment]
Can you test this again on the latest version?
