### ISSUE TITLE
Website tabs overlapping on small screens

### ISSUE THREAD

**Issue by LukePrior** [dl9rdz/rdz_ttgo_sonde#149]
**Describe the bug**
The page tabs on the web interface overlap when using a narrow screen such as a mobile device.

![Screenshot_2021-09-02-15-49-08-33_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/22492406/131789157-b63f31e3-8b1d-4293-8ce9-301efdfe8cc9.jpg)

**Expected behavior**
I think it would be good that if the screen is too narrow two rows are shown. This can be observed when resizing the page on desktop quickly.

**Version and specific configuration:**
 devel20210817

**Comment by dl9rdz** [comment]
Yes I noticed that on my smartphone as well. I am open for design suggestions.

Two lines might be an option, but would use up much space on a small smartphone display so it is not my favorite option.

As we now have the integrated lLiveMap, maybe the "Map" could be removed (there are direct link to several external mapping services in the Data tab anyway), and LiveMap renamed to Map?

Maybe the font size of the tabs could be adjusted depending on the screen width?

**Comment by LukePrior** [comment]
> Two lines might be an option, but would use up much space on a small smartphone display so it is not my favorite option.

Yeah good point

> As we now have the integrated lLiveMap, maybe the "Map" could be removed (there are direct link to several external mapping services in the Data tab anyway), and LiveMap renamed to Map?

That sounds ok the only reason I added it was due to the lack of a local map, just be sure to remove all the code

> Maybe the font size of the tabs could be adjusted depending on the screen width?

This should probably also be added

**Comment by eben80** [comment]
Hi all,
I'm no UX designer by any means but I came up with some kind of responsive menu.
When there is enough space to display the menus in landscape orientation, it will display the full menus:
![2021-09-08 14_52_19-rdzTTGOSonde Server](https://user-images.githubusercontent.com/2545460/132512747-df5f41ff-0d96-4724-9bcb-c733b071af9e.png)
When the device is in portrait orientation and there is not enough space to display the menus, it is collapsed into a "hamburger menu"
![2021-09-08 14_52_07-rdzTTGOSonde Server](https://user-images.githubusercontent.com/2545460/132512780-dbb2aa97-7025-4d79-9747-fee099e66124.png)
![2021-09-08 14_52_33-rdzTTGOSonde Server](https://user-images.githubusercontent.com/2545460/132512823-5be40b76-9cf6-4d97-ad38-a8f45802b9c8.png)

If it is of interest to you I could do a pull request with the changes. Of course it can be even more customized.

**Comment by eben80** [comment]
Changes [HERE](https://github.com/eben80/rdz_ttgo_sonde/tree/responsiveui)

**Comment by LukePrior** [comment]
I like the look of it much better than the existing solution.

**Comment by eben80** [comment]
OK I'll create a PR for it and you can configure it as you like. Just remember to see changes a Shift+F5 reload is needed unless you change the stylesheet name.

**Comment by eben80** [comment]
@LukePrior did you try it out already?

**Comment by LukePrior** [comment]
> @LukePrior did you try it out already?

I updated with OTA and did a Shift-F5 refresh but didn't see the changes so I'm assuming I will need to manually flash it.

**Comment by eben80** [comment]
Oh yes I see the OTA is from the 14th so perhaps the new changes are not included yet. Manual flashing should have it now.

**Comment by dl9rdz** [comment]
The OTA update does not update the files (stuff in RX_FSK/data), only the code part.
If you don't want to re-flash, you could also do the update for the relevant file (style.css) via WiFi with 
```
cd RX_FSK/data
python3 ../../scripts/ttgoconfig put file style.css
```
add `--ttgo=<ip>` if you have a system without working mdns discovery

**Comment by LukePrior** [comment]
Ok,

I have updated and can see the changes. I do note that there seems to be a small issue of the elements not lining up:
![image](https://user-images.githubusercontent.com/22492406/133702404-75b2a5aa-cda6-4994-95d8-952a0e814c15.png)
![image](https://user-images.githubusercontent.com/22492406/133702450-5e6d1555-0ae9-4916-b370-f8b4ded7962b.png)
Not sure if these are intentional.

**Comment by eben80** [comment]
Those are not intentional, I think they came it when I included the hamburger icon in css. Will see if I can match it exactly like before soon.

**Comment by LukePrior** [comment]
> Will see if I can match it exactly like before soon.

Just tested and works perfectly Thanks
