### ISSUE TITLE
devel update 

### ISSUE THREAD

**Issue by 14ri004** [dl9rdz/rdz_ttgo_sonde#159]
a bug in the display on my ttgo, after downloading the new devel

![20210913_082705](https://user-images.githubusercontent.com/87615097/133134038-4242078c-a79d-45d0-8252-0d9de6da2f92.jpg)
![20210913_082707](https://user-images.githubusercontent.com/87615097/133134053-c47c950f-640b-4d19-9cef-81c7c174eb4d.jpg)

**Comment by LukePrior** [comment]
Hey,

Can I see a copy of your configuration settings for SondeHub as that was where all the updates were made.

Cheers

**Comment by 14ri004** [comment]
hello, it's a ttgo t beam

![sondehub](https://user-images.githubusercontent.com/87615097/133212919-ee8953f0-ba1b-443a-9e35-6affcc7cdffe.JPG)

**Comment by LukePrior** [comment]
Hmm it must be related the code reformat and not the SondeHub changes as you have that disabled.

**Comment by dl9rdz** [comment]
This is not a new problem, this has been that way all the time.
The OTA code is from a time where only OLED displays were supported, and the y position (lines on the OLED) is hard-coded in +1 increments (for the TFT display, it is now "pixels").

**Comment by 14ri004** [comment]
Thank you for your answers, it was just to inform you of the problem on the screen, it does not bother the operation of the TTGO
