### ISSUE TITLE
Empty QRG tab on version >= devel20210916

### ISSUE THREAD

**Issue by 14ri004** [dl9rdz/rdz_ttgo_sonde#171]
hello, after updating the devel20210916 version in OTA, I no longer have a QRG table on the TTGO server, same problem on 3 TTGO, have to reinstall the file and redo the complete config

![BUG](https://user-images.githubusercontent.com/87615097/133772944-fa38d4fd-4fb6-457a-a3dc-ca947c6e38c0.JPG)

**Comment by dl9rdz** [comment]
You have to do the OTA twice.
First to update the software (which adds functionality to the software to do OTA update of some files on the SPIFFS)
Then to update the files on the SPIFFS.
Possible then also to a Ctrl+F5 or similar in the browser to update files (css/js) that the browser might have cached.

**Comment by 14ri004** [comment]
Thank you, indeed with CTRL + F5 problem to be solved, well done
