### ISSUE TITLE
Western Hemisphere Longitude Issue with Burst and Landing Predictions

### ISSUE THREAD

**Issue by WH3080** [dl9rdz/rdz_ttgo_sonde#172]
I am truly impressed how this software has evolved. I am using it in North America. For the first time the prediction function now works for me on the live map (not on the rdzwx-go app though). 
While the predicted landing site is accurately displayed on the live map, the indicated longitude is always off by 180 degrees, i.e. negative lon won't show properly. That means forwarding to Google Maps or other maps doesn't work. I believe there is a calculation bug somewhere which is not apparent to Eastern Hemisphere users that mainly use your fantastic software.

**Comment by dl9rdz** [comment]
Thanks for the report. Indeed, our previous fix only solved parts of the problem, the label and link to maps still contained the value as returned from tawhiri, instead of moving it to the -180..180 range.
Should be fixed in the next version. Make sure to refresh the browser cache.

**Comment by WH3080** [comment]
Thank you! Your prompt help is greatly appreciated!

**Comment by dl9rdz** [comment]
Closing this issue, as it should be fine now.
