### ISSUE TITLE
adding a function

### ISSUE THREAD

**Issue by 14ri004** [dl9rdz/rdz_ttgo_sonde#177]
Hello, is it possible to have the distance between the Probe / QTH of the station on the LiveMap, thank you

**Comment by dl9rdz** [comment]
This function was already there if station QTH had a GPS position (from the ttgo internal gps).
The latest update also uses the fixed position from config if GPS position is not available.

**Comment by eben80** [comment]
I can confirm this works.
It's displayed at the bottom of the map as you can see below:
![image](https://user-images.githubusercontent.com/2545460/133975802-d782b06a-f17c-45ea-b5b9-cf22d31b4d95.png)

**Comment by 14ri004** [comment]
Hello, indeed I see the distance now, thank you
