### ISSUE TITLE
Burst Timer only ever returns 30600

### ISSUE THREAD

**Issue by LukePrior** [dl9rdz/rdz_ttgo_sonde#179]
Hi,

The code I added yesterday to upload burst_timer values to SondeHub works correctly but I believe that the decoded value is incorrect. I have checked SondeHub and the only value ever uploaded by rdzTTGOsonde is 30600 even when the value reported by auto_rx for the same frame is different. This leads me to believe that there is an issue with the decoder.

![image](https://user-images.githubusercontent.com/22492406/133951430-20bd57a9-fc93-4558-8976-462f26a15f91.png)

I believe we get the burst timer value here: https://github.com/dl9rdz/rdz_ttgo_sonde/blob/devel/RX_FSK/src/RS41.cpp#L701
This is how auto_rx calculates it: https://github.com/projecthorus/radiosonde_auto_rx/blob/master/demod/mod/rs41mod.c#L1177

**Comment by dl9rdz** [comment]
Well, autorx calls it "bt" in the json, but it does not include the bt value there, but instead the countdown value cd...
https://github.com/projecthorus/radiosonde_auto_rx/blob/edf32f50078d26dc105e83d556eddd2647f8b13e/demod/mod/rs41mod.c#L1820
`                        fprintf(stdout, "[...], \"bt\": %d, \"batt\": %.2f", [...] gpx->conf_cd, gpx->batt );`
cd is s->countKT in my code.

**Comment by LukePrior** [comment]
> Well, autorx calls it "bt" in the json, but it does not include the bt value there, but instead the countdown value cd...

That explains it sorry for the confusion.

Would you like me to open a PR to change to the uploaded value to countKT?

Is that value also 0 if it has not yet been decoded?

**Comment by LukePrior** [comment]
Ok, so it appears that rdzTTGOsonde reports -1 when auto_rx reports 65,535 which I'm guessing is something to do with how the 16-bit value is handled.

**Comment by dl9rdz** [comment]
Yes, that should better be an uint16 instead of an int16. Will change that in the next version.

**Comment by eben80** [comment]
> Ok, so it appears that rdzTTGOsonde reports -1 when auto_rx reports 65,535 which I'm guessing is something to do with how the 16-bit value is handled.

Doesn't countKT  report -1 once the countdown reaches 0?

![image](https://user-images.githubusercontent.com/2545460/134060818-358dbbc8-1e68-4221-9bc9-dee1cf9e951e.png)

![image](https://user-images.githubusercontent.com/2545460/134060969-22ad97cd-6813-45ff-880a-b5084af26e1d.png)

It's been working OK for me in my data tab and screen displays.

**Comment by eben80** [comment]
Ok I saw on last night's data that its also - 1 before the countdown is triggered.

**Comment by LukePrior** [comment]
I think the latest update should mean that this is now in line with auto_rx and will close this issue once I see some data in SondeHub.

**Comment by LukePrior** [comment]
Hmm the values seem slightly off:

![image](https://user-images.githubusercontent.com/22492406/134160758-24b34638-e965-4c98-bbfc-c0d44519a83a.png)

**Comment by dl9rdz** [comment]
That is expected to happen.

The counter value is sent only every 51 frames. If the value is not updated, we send the previously captured value. If we have a CRC error on the frame with the counter, we skip on update, so it is possible to lack 51 (or multiples thereof) behind. This behaviour should be consistent with autorx. So even with two autorx (unless I missed something in the code), you might see such situations if one station is receiving a weak signal with crc errors.

My software actually stores the frame number for which the counter was last updated. We could use that to predict the "real" countdown value (as countKT + frame - crefKT).

**Comment by LukePrior** [comment]
> The counter value is sent only every 51 frames. If the value is not updated, we send the previously captured value. If we have a CRC error on the frame with the counter, we skip on update, so it is possible to lack 51 (or multiples thereof) behind. This behaviour should be consistent with autorx. So even with two autorx (unless I missed something in the code), you might see such situations if one station is receiving a weak signal with crc errors.

That makes sense I will close this issue.

> My software actually stores the frame number for which the counter was last updated. We could use that to predict the "real" countdown value (as countKT + frame - crefKT).

Hmmm interesting, but I think it is probably best to only upload what the sonde has sent so we match auto rx.

**Comment by mycarda** [comment]
> Hmmm interesting, but I think it is probably best to only upload what the sonde has sent so we match auto rx.

I was thinking the same thing. Do we have to send the value every time or can we just send the value when the corresponding 16 byte subrame block is received? The only issue would be if any of these values span a single 16 byte block but I don't think any of them do.

**Comment by LukePrior** [comment]
> Do we have to send the value every time or can we just send the value when the corresponding 16 byte subrame block is received?

I think sending it every frame is fine but maybe we can not send it if it has been over 51 frames and we don't have a new value.

**Comment by dl9rdz** [comment]
Ok, that makes sense. Tried to implement that in the last commit, but without testing.
