### ISSUE TITLE
Strange Temperature & Humidity Values RS41

### ISSUE THREAD

**Issue by LukePrior** [dl9rdz/rdz_ttgo_sonde#185]
I was looking at some data and saw something weird happening with a `devel20210921` station. The uploaded temperature and humidity values were sent as an incorrect constant for about a minute before matching auto_rx, could this be something with calibration values?

Here is the data:
![image](https://user-images.githubusercontent.com/22492406/134274067-24c292c1-8798-480b-9008-7cc06061711a.png)
![image](https://user-images.githubusercontent.com/22492406/134274092-da45877e-1387-4149-aa91-5804b0ef203e.png)

Any ideas @mycarda @dl9rdz

**Comment by mycarda** [comment]
@LukePrior
Is 02:53:45 the time we started sending the temperature and humidity values or are you just showing part of the whole chart. The reason I ask is I would expect the temperature to be available maybe 30 seconds before the humidity value.

Also, both the temperature and humidity start behaving nicely at exactly the same time. As humidity is dependent on temperature, if there is a problem with the calibration values or calculation it would point to the temperature being the issue although I would expect some variation in the temperature and humidity, not just a fixed value (which what appears on the chart).

Finally, when we decide to send the temperature
https://github.com/mycarda/rdz_ttgo_sonde/blob/8a62085f4f362a009a041abf6b52fc14756c2f0d/RX_FSK/RX_FSK.ino#L3720
how do we know the value is a valid calculation and not just anything other than zero?

Sorry. all questions so far and no answers.

**Comment by mycarda** [comment]
> I would expect the temperature to be available maybe 30 seconds before the humidity value.

Having said that, the launch I monitored this morning happened to get all the humidity calibration blocks first and the temperature calibration ones last so it's not always the case - just usually. :-)

**Comment by LukePrior** [comment]
Hey,

The serial number of the aforementioned sonde was: S3130783.
The station uploading the data was: Test_Heiko_1_1_RDZTTGO

> Is 02:53:45 the time we started sending the temperature and humidity values or are you just showing part of the whole chart.

The first packet from this station for this sonde was at 02:53:49 which is the first packet shown in the images above.

> I would expect some variation in the temperature and humidity, not just a fixed value

I can confirm that the value was constant which alerted me to the data initially.

- Humidity: 58.511
- Temperature: -42.99

> how do we know the value is a valid calculation and not just anything other than zero?

We do not, if you have any suggestions to improve that I would love to hear them.

> Sorry. all questions so far and no answers.

Not at all, thanks for your time looking into it.

**Comment by eben80** [comment]
It happened with me yesterday lunchtime for the first few minutes with a devel20210920 build before it corrected itself.

The flight is attached below and the nice thing is you have data from 2 different auto_rx versions plus SondeMonitor(who has a problem with sonde bearing)
I didn't see the same problem with the last midnight flights.
[response_1632231373417.xlsx](https://github.com/dl9rdz/rdz_ttgo_sonde/files/7208612/response_1632231373417.xlsx)

**Comment by LukePrior** [comment]
> SondeMonitor (who has a problem with sonde bearing)

This is undergoing updates and the latest is now 6.2.5.2 so that may well be fixed.

**Comment by dl9rdz** [comment]
Ok, I will fix this (see #186 last item that I just added)

**Comment by mycarda** [comment]
> We do not, if you have any suggestions to improve that I would love to hear them

Initially, I think the values are set to impossible values
https://github.com/mycarda/rdz_ttgo_sonde/blob/ab1da6ea9aacc4a507f31aeec816c9d043a8b590/RX_FSK/src/Sonde.h#L111-L113
So maybe check those.

I think it might be more reliable to explicitly mark the values as invalid when we check if we have the required calibration values
https://github.com/mycarda/rdz_ttgo_sonde/blob/ab1da6ea9aacc4a507f31aeec816c9d043a8b590/RX_FSK/src/RS41.cpp#L769-L773
by adding
`else si->temperature = -300.0` or maybe `si->temperature = NAN`

Similarly for humidity.

**Comment by dl9rdz** [comment]
The wrong values are most likely old values from a previous sonde that remain there as long as we don't have new calibration data for calculating new values. 

I added some code that now clears all data, including temperature etc., whenever the calibration data is cleared (manual config change, new ID detected). This should solve this issue.

**Comment by mycarda** [comment]
> Initially, I think the values are set to impossible values

I was wrong. The value of the temperature before we calculate it is 0.0 which is probably why the existing check works so well. Technically, this might be a valid value at some point in the flight as, technically, so is 0.0 humidity.

**Comment by dl9rdz** [comment]
In the latest update, Sonde::clearAllData() sets all floats to NAN. that includes position and temp/humitidy.
Its called from RS41.cpp whenever a new ID is detected.
(I will have a closer look at the non-RS41 decoders, but it should be less an issue elsewhere)

**Comment by LukePrior** [comment]
> In the latest update, Sonde::clearAllData() sets all floats to NAN. that includes position and temp/humitidy.

Will these checks need to be changed in that case?

https://github.com/dl9rdz/rdz_ttgo_sonde/blob/devel/RX_FSK/RX_FSK.ino#L3719

**Comment by dl9rdz** [comment]
yes
