### ISSUE TITLE
M10 type in qrg.txt indicated like M20 in DATA web server

### ISSUE THREAD

**Issue by F5MVO** [dl9rdz/rdz_ttgo_sonde#197]
qrg.txt
402.004 M - Bordeaux
401.000 M - Trappes
402.000 M - Trappes
404.800 2 - URY
405.200 2 - URY
=======================================================
404.004 MHz, Type: M20
ID:
QTH: nan,nan h=nanm
Frame# 0, Sats=0, 1970-01-01 00:00:00
GEO-App - radiosondy.info - SondeHub Tracker - OSM - Google

Do not interfere the decoding

**Comment by eben80** [comment]
I noticed this yesterday as well.
