### ISSUE TITLE
Problem with DFM09 ?

### ISSUE THREAD

**Issue by F5MVO** [dl9rdz/rdz_ttgo_sonde#200]
![Sélection_005](https://user-images.githubusercontent.com/88462347/135417043-ccd89efc-569a-4a85-8d38-3b47705c408f.png)

**Comment by dl9rdz** [comment]
Yes, checking for bit errors was not really well done.
Should be better in today's update.

**Comment by LukePrior** [comment]
I'm sure the error checking plays some role in this but DFM is notorious for bad data in my experience. We have a few checks in the SondeHub backend to attempt to find these obviously incorrect frames but it is tricky to do right. The checks should help minimise this however as we found most of the bad frames were uploaded from rdzTTGOsonde.
