### ISSUE TITLE
Meteomodem M10 Battery Voltage & Humidity

### ISSUE THREAD

**Issue by LukePrior** [dl9rdz/rdz_ttgo_sonde#205]
We now have battery voltage decoding for RS41 and DFM so I think it would also be good to have for M10. The M10 is the 3rd most popular sonde decoded by this software after RS41, and DFM. The code for battery voltage decoding in auto rx can be found here: https://github.com/projecthorus/radiosonde_auto_rx/blob/master/demod/mod/m10mod.c#L828

The addition of Humidity decoding would bring this in line with auto rx but given the complexity and scope, you may wish to exclude it. The code can be found here if interested: https://github.com/projecthorus/radiosonde_auto_rx/blob/master/demod/mod/m10mod.c#L774

**Comment by dl9rdz** [comment]
Should be ok

**Comment by LukePrior** [comment]
Yep it's all perfect,
