### ISSUE TITLE
Suggestion: LiveMap.js  geo link mod

### ISSUE THREAD

**Issue by lucaswl653** [dl9rdz/rdz_ttgo_sonde#231]
Using Android 11 browser, Live Map "geo:" a href: links don't work.
I solved it by editing Livemap.js  like this 
 
![immagine](https://user-images.githubusercontent.com/85156519/139239181-8cdea3d7-02d5-45c2-a2f1-3d323b08505e.png)

**Comment by cixio** [comment]
Pull request for fix here: https://github.com/dl9rdz/rdz_ttgo_sonde/pull/298/commits/a3a26ae471338860e91b80143110d27d82169bc0

**Comment by cixio** [comment]
Fixed with #298 
Issue can be closed.
