### ISSUE TITLE
Problems with Display OLED 1306

### ISSUE THREAD

**Issue by smarti2019** [dl9rdz/rdz_ttgo_sonde#24]
Problems with OLED display 1306. When i press the buttons to reach the individual menu items, the display regularly crashes. So it is only confused characters are displayed.
Any Ideas?

**Comment by smarti2019** [comment]
![Uploading 86914951...]()

**Comment by smarti2019** [comment]
![7nV0i7o2R6G7cR0jEMui_Q](https://user-images.githubusercontent.com/47259711/86915496-59ed6380-c122-11ea-881f-4f9094367795.jpg)

**Comment by smarti2019** [comment]
_

**Comment by dl9rdz** [comment]
Can you check if this problem also happens if you use a touch pin as button instead of the power button?

**Comment by smarti2019** [comment]
how do I implement a touch pin on the ttgo beam board?

**Comment by smarti2019** [comment]
Ok i have found the Touch PIN. With this configuration and use of the touch pin, it works. But it would be nice if the existing buttons on the TTGO beam would work without a crash.
![2020-07-08_19-55-05_000](https://user-images.githubusercontent.com/47259711/86954184-d3eb1000-c155-11ea-8820-f2e1799f8720.jpeg)

**Comment by dl9rdz** [comment]
Can you test devel20201111b? It should fix the problem, but I misplaced my LCD display for the T-Beam to test myself.

**Comment by smarti2019** [comment]
I Have just tested the latest devel20201111b version. The display problem has been resolved and the power button can be used as button 2. Absolutely perfect.
At this point, a big, big thank for you for this ingenious software!
