### ISSUE TITLE
M20 Serial inconsistency

### ISSUE THREAD

**Issue by eben80** [dl9rdz/rdz_ttgo_sonde#263]
**Describe the bug**
While following an M20 sonde on livemap, the marker keeps on jumping around and creating new predictions because the Serial number(id) of the M20 Sonde is inconsistent.
![2022-01-05 14_29_15-rdzTTGOSonde Server LiveMap](https://user-images.githubusercontent.com/2545460/148225710-99332474-d9db-4a81-af5c-721e8416c3fe.png)

This doesn't happen with RS41 sondes. This is the first time I'm receiving a M20 so I don't know if this is normal.

**Comment by dl9rdz** [comment]
Should be fixed in the latest devel (20210123)
