### ISSUE TITLE
Screen off after last dev update

### ISSUE THREAD

**Issue by dreamfalcon** [dl9rdz/rdz_ttgo_sonde#300]
After the last dev updated the screen never turns on.
Tried reverting to the master but same problem.
Probably a hardware problem!?

**Comment by eben80** [comment]
The green led flashes once during startup?

**Comment by dreamfalcon** [comment]
Yes.
The web interface works fine.

**Comment by eben80** [comment]
How are you flashing it? With platformIO or the flasher?
It might be an issue with the data files.
Perhaps try a full flash if you're using the flasher or reflash the filesystem if using platformio.

**Comment by dreamfalcon** [comment]
Was using OTA.
But now used the esptool and same problem. Probably a harware problem :(
esptool --chip esp32 --port COM3 --baud 921600 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 80m --flash_size detect 0x1000 master_v0.9.1-B16-full.bin

**Comment by eben80** [comment]
It might we worth erasing the flash and then flashing the original paxcounter software just to make sure it's a hardware issue.
