### ISSUE TITLE
screen IP address

### ISSUE THREAD

**Issue by 14ri004** [dl9rdz/rdz_ttgo_sonde#306]
good evening, small question, is there a possibility for the ip address of my TTGO of my car, not to overlap between the address of my box and my telephone, the last 2 digits remain visible on the screen and they are added to the new ip address, when I go from the box 192.168.1.54 to the phone 192.168.43.211 and from the phone to the box = 192.168.43.211 to finish at 192.168.1.5411
what would be the solution, thanks.

![20220531_163928](https://user-images.githubusercontent.com/87615097/171233776-4f270259-e027-458e-a2d7-3dd1eac4996d.jpg)

**Comment by dl9rdz** [comment]
Never tested that with changing IP addresses :)
You can specify the width of the output in screens<X>.txt
Repliace "7,5=n" with something like "7,5,15=n"
(adjust the 15 such that it is as wide as necessary, but still within the screen)

**Comment by 14ri004** [comment]
7,2=n

thank you, i will try other values

**Comment by 14ri004** [comment]
thanks hansi, it works perfect with 7,2,-15=n
