### ISSUE TITLE
ili9341 2.8" vs ili9341 3.2" (resolved)

### ISSUE THREAD

**Issue by 14ri004** [dl9rdz/rdz_ttgo_sonde#309]
Hello Hansi, I have just received 2 news ili9341 v1.2 screens in 2.8", these are not the same screens as the previous version (ST7789), the 2 screens are well taken in Type-3 (ili9341), but also I find myself like the other day with a white band on the side of the screen, there is still text visible in this white band, it becomes really annoying, thank you in advance if there is a solution to this problem .

![20220614_105726](https://user-images.githubusercontent.com/87615097/173540504-2bd3c25b-2151-481f-b0c0-f4af7eab5e36.jpg)

![20220614_105852](https://user-images.githubusercontent.com/87615097/173540540-822c17f9-0ed3-429c-b8e6-c9759245a43e.jpg)

**Comment by 14ri004** [comment]
![20220615_110655](https://user-images.githubusercontent.com/87615097/173789653-f6f18f71-64f3-4a46-939f-c64da526fbb8.jpg)

**Comment by 14ri004** [comment]
the 2.8" screen has a white stripe, while there is none on the 3.2"

the ili9341 2.8"
![20220616_111403](https://user-images.githubusercontent.com/87615097/174457547-2c1762f7-33ab-4927-8484-0093e9f76d17.jpg)

the ili9341 3.2"
![20220618_203044](https://user-images.githubusercontent.com/87615097/174457551-6575d43d-c38a-416f-b94f-54d5b524799b.jpg)

**Comment by dl9rdz** [comment]
Ok, strange, so the first question might be is this possibly a hardware defect?

Did you try using the display with different software? You could try example software from some of the (mulitple) available ILI9341 libraries. 
- https://github.com/moononournation/Arduino_GFX (the library I am using, it contains some example applications)
- https://github.com/schreibfaul1/ESP32-TFT-Library-ILI9341-HX8347D
- https://github.com/loboris/ESP32_Adafruit_ILI9341
Note that they might require a different wiring or adjustment in the code...

**Comment by 14ri004** [comment]
Good evening Hansi, no I did not try the screens on anything else, I checked the wiring on the ttgo 3 times, the 2.8 screens are in version 1.2 and the 3.2 screen is in version 1.0, again our Chinese friends who changed something??

**Comment by 14ri004** [comment]
Hello hansi, the problem comes from a screen that would be out of service, I put the second screen which works perfectly, so problem solved, thank you
