### ISSUE TITLE
elevation of the probe

### ISSUE THREAD

**Issue by 14ri004** [dl9rdz/rdz_ttgo_sonde#320]
Hello, is it possible to have the elevation of the probe on LiveMap and TTGO compared to the GPS point of the TTGO, as on SondeHub

thank you

![elevation](https://user-images.githubusercontent.com/87615097/182169917-7426fcb8-e107-4db2-9a95-785e19b9b40b.JPG)

**Comment by dl9rdz** [comment]
On the LiveMaop it should be no big issue, I can add it to the todo list (or will pull requests for that - I did not implement the LiveMap part myself).
On the TTGO, the calculation would require quite some part in the very small space for the code, so it is not likely to be added (or possibly configurable in source code, for compiling yourself if you leave away other parts to gain more free space)

**Comment by 14ri004** [comment]
hello, and thank you for your answer, too bad for the lack of space, this function would be interesting on the TTGO for monitoring Probes, thank you
