### ISSUE TITLE
Run software on M5 Stack Basic Core ?

### ISSUE THREAD

**Issue by WH3080** [dl9rdz/rdz_ttgo_sonde#321]
Hello and apologies in advance for another newbie question / request. I tried to flash the latest development .bin onto an M5 Stack Core Basic: https://shop.m5stack.com/products/esp32-basic-core-iot-development-kit-v2-6 However, while the process described here: http://rdzsonde.mooo.com works perfectly for the TTGO boards, it fails for the M5 Stack Core Basic. The board appears to be intact. I am able to install Tasmota onto it, albeit only via the web interface and not through uploading the .bin file. What am I doing wrong? Any help is greatly appreciated. Thank you!

**Comment by dl9rdz** [comment]
There is no direct support for the M5 Core (yet), only for the Core2, which has different internal wiring.

It probably is not much work to adjust things properly, but directly using the binary firmware will not work.
Instead some changes to the code, in particular the non-configurable part in RX_FSK.ino (for setting up the power management controller) needs to be changed in source code.
