### ISSUE TITLE
probe distance in Meters

### ISSUE THREAD

**Issue by 14ri004** [dl9rdz/rdz_ttgo_sonde#331]
good evening, when the probe is more than 100km away it's good, but at 99km the distance indicates meters, would it be possible to have the distance in meters from only 1000 meters, thank you

![20221102_135452](https://user-images.githubusercontent.com/87615097/199556675-1cf12bce-9066-498c-bb2e-76739cd095a5.jpg)

**Comment by hr-ru** [comment]
In the screens file, you can change GD to GD5 for getting a 5-digit-version (including the unit), so it will be km for anything >= 10km, and meters below (i.e. you will have 10.0km but then 9999m). Is that good enough?

**Comment by 14ri004** [comment]
Hello, I tried GD5 but unfortunately it does not work, I always have the figures in Meters below 100km

**Comment by 14ri004** [comment]
hello, still no solution to have the distance of the probe in Meters and only below 10km, up to 100 km it's ok, but below it goes to 99999 m instead of 99 km, I have test the GD5 manipulation but it does not change the result, is there a solution, thank you

**Comment by dl9rdz** [comment]
Are you sure you changed the right file and/or screen? I cannot test it myself right now, but this *should* work.
I can check myself later some time in December.

**Comment by 14ri004** [comment]
hello, yes change made in the correct screen and on 2 ttgo, it does not change the result on the distance of the probe, above 100 km ok, but below it is in meters 99999m

**Comment by kmp56** [comment]
confirmation,  GD5 change nothing....  (LoRa32 V2.1 _ 1.6)

**Comment by dl9rdz** [comment]
Alright, there is a bug. Or was. Should be fixed in devel20221217 (without testing)

**Comment by kmp56** [comment]
≤ 100km is ok, still km, e.g. 42km also km. I can't check ≤ 10km - the probe is too far unfortunately. I hope there will be meters...

**Comment by dl9rdz** [comment]
Yes, <10km it should be meters.

**Comment by 14ri004** [comment]
Hello, indeed it works in KM below 100 km, I'm waiting to see below 10km, but it seems perfect to me, thank you and have a good Sunday

**Comment by kmp56** [comment]
So everything should work ok ;) BTW the test sonde on my balcony shows correctly - meters. 
Thanks for the great job!  Merry Christmas!

**Comment by 14ri004** [comment]
![Uploading 20221218_140006.jpg…]()

**Comment by 14ri004** [comment]
![20221218_140006](https://user-images.githubusercontent.com/87615097/208299900-df8bf117-78bb-4515-a0b7-089024e6823d.jpg)
