### ISSUE TITLE
Location of tracker not on Sondehub

### ISSUE THREAD

**Issue by efiten** [dl9rdz/rdz_ttgo_sonde#337]
**Describe the bug**
When I run my tracker (ESP32 or T-beam), the location is not published in the Sondehub map.

**To Reproduce**
This happens to both trackers that I test, always.

**Expected behavior**
Location visible

**Version and specific configuration:**
 - What firmware version are you using? Used master BIN file (version master_v0.9.2)
 - Hardware you are using? TTGO LORA32 board & TTGO T-beam

**Additional context**
I've set the mode to FIXED and filled in my GPS location :
![image](https://user-images.githubusercontent.com/11015082/204762661-f7fd8322-d28c-4efa-a8a9-55a8adb7d4d5.png)
On the livemap inside the internal page, I'm visible : 
![image](https://user-images.githubusercontent.com/11015082/204762861-9340a57a-16b6-4d79-82fe-eb6253bfb598.png)

**Comment by efiten** [comment]
Left the device online for some, and it looks like it doesn't even sent the data to Sondehub. Do I miss something? Setting reporting to '1', set the callsign, that's it ?

**Comment by 14ri004** [comment]
![204762861-9340a57a-16b6-4d79-82fe-eb6253bfb598](https://user-images.githubusercontent.com/87615097/207300243-9dd2325b-91ed-4f03-85d2-cacdb7ddba43.png)

hello, why Rdzsonde-2 ????

**Comment by efiten** [comment]
Because I'm running 2 board, as a test, so I can see what board I'm working
with during test.

Op di 13 dec. 2022 om 12:01 schreef 14ri004 ***@***.***>:

**Comment by titoaprendiz** [comment]
Olá!
Eu também estava com o mesmo problema, mas tudo foi resolvido com a instalação de novo browser.
Eu usava chrome e fireFox, e dava erro nos dois navegadores
Fiz a instalação do Opera, mas não importei as configurações dos dois navegadores.
Refiz todo procedimento de instação e tudo funcionou perfeitamente bem.
73 de Tito Augusto, PU2OZK.

**Comment by DG0MG** [comment]
@efiten 
Please try to set "SondeHub location reporting" to **3** (automatic, not fixed). 
I remember, i had the same problem at the beginning of my fixed receiver station.

**Comment by 14ri004** [comment]
Merci pour votre réponse, je vais essayer cette solution et voir si cela fonctionne, merci Envoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : DG0MG ***@***.***> Date : 27/12/2022  16:12  (GMT+01:00) À : dl9rdz/rdz_ttgo_sonde ***@***.***> Cc : 14ri004 ***@***.***>, Comment ***@***.***> Objet : Re: [dl9rdz/rdz_ttgo_sonde] Location of tracker not on Sondehub
  (Issue #337) 
@efiten
Please try to set "SondeHub location reporting" to 3 (automatic, not fixed).
I remember, i had the same problem at the beginning of my fixed receiver station.
