### ISSUE TITLE
1.3" OLED - Display not working in Spectrum Mode

### ISSUE THREAD

**Issue by df2ap** [dl9rdz/rdz_ttgo_sonde#34]
I use RDZSonde on an TTGO T-Beam V1. The OLED-Display is an 1.3" OLED-Display SH1106. I flashed the BIN-File. Until Version 0.7.1 everythink working fine.

Now I flashed completly new with Version 0.8.0 Master. I made the right Configuration also new.

Everything works fine, but not the Spectrum Mode. There are only in the upper Part of the Display some Work.

![IMG_8739](https://user-images.githubusercontent.com/47256877/99186569-709b6b00-2751-11eb-93d8-95b7253d81f5.jpg)

**Comment by cixio** [comment]
Same here, used: master_v0.8.0-B4-full.bin (Nov 11 07:51:45 2020)

**Comment by dl9rdz** [comment]
Ah, thanks, I forgot about the SH1106 (which currently is treated the same way as the TFT, not the LCD, for configuring the spectrum layout)... update coming soon

**Comment by dl9rdz** [comment]
Should be fixed in devel-20201115. (I don't have a SH1106 display to test)

**Comment by df2ap** [comment]
It works! 

Thank you very much.
