### ISSUE TITLE
Severe problem in U8x8Display::drawString

### ISSUE THREAD

**Issue by buttim** [dl9rdz/rdz_ttgo_sonde#342]
Line 321 of Display.cpp reads:
`memset(buf, ' ', width-l);`
but is contained in the if clause
`if(width<0) {`
so apparently if `width<0` it is going to erase most of the memory.
I think it should be corrected to:
`memset(buf, ' ', -width-l);`

**Comment by dl9rdz** [comment]
Good point, thanks for this information.

In practice the feature with negative width (=right-justified text) has only been used for the TFT displays, not the OLED display (at least not with the default layout in screens1.txt, and the comments in there indicate that right-justified text is only supported with the TFT display).

But of course you are right, this code that actually implements right-justified text for OLED is wrong, and should be fixed.
