### ISSUE TITLE
tdzsonde.mooo.com gone

### ISSUE THREAD

**Issue by tfholdings** [dl9rdz/rdz_ttgo_sonde#352]
the website tdzsonde.mooo.com is no longer available on mooo.com.  any idea where the tool can be found?

**Comment by hr-ru** [comment]
It still is, and always has been, https://rdzsonde.mooo.com/

**Comment by tfholdings** [comment]
It came back, not sure what was wrong.  Maybe dns.  I did a search on mooo.com and the search could find it either.  Glad it's back.
