### ISSUE TITLE
SNR SondeHub reporting

### ISSUE THREAD

**Issue by joevk5ei** [dl9rdz/rdz_ttgo_sonde#356]
It appears noise floor is reporting to SondeHub rather than actual SNR of sonde signal tracked

**Comment by Szetya** [comment]
SNR only works in lora mode. Not in FSK mode.

**Comment by darksidelemm** [comment]
Yep, what the rdz_ttgo_sonde units are reporting is received power level (hence it being displayed as dBm, not dB). This is the best the lora chipsets will do in FSK mode I think, and tbh is fine.

**Comment by joevk5ei** [comment]
Ok, understood
