### ISSUE TITLE
Changed screens.txt by error

### ISSUE THREAD

**Issue by puspis** [dl9rdz/rdz_ttgo_sonde#37]
Hi. I am newbie in Github and I think I have changed the original screen.txt file by my own (modified) by mistake. Sorry for the inconveniences. If you want, you can add my changes to the screens.txt file
![photo5834458354741785736](https://user-images.githubusercontent.com/27033536/99875743-2a7f5500-2bf2-11eb-844d-f707f5148504.jpg)

**Comment by dl9rdz** [comment]
You changed it in your fork, but its a nice alternative, will be glad to add it as an additional alternative in my next version.

**Comment by puspis** [comment]
OK. See my screens.txt for other variations on the screens, ony for ILI9225 TFT.
Many thanks for your work. It's superb in combination with APRSdroid app.
