### ISSUE TITLE
WiFi password length problems.

### ISSUE THREAD

**Issue by JDat** [dl9rdz/rdz_ttgo_sonde#372]
I have 30 character long WiFi password on my router.
Looks like RDZsonde code support only up to 8 characters.
Can you increase WiFi password length to 30 characters?

**Comment by dl9rdz** [comment]
No, there is no limitation in password size in my code.
(ESP32 code might limit password length to 32 characters I think)

**Comment by dl9rdz** [comment]
Just as a quick follow-up, maybe another possibilityis that you have some special characters in the password that are not handled correctly by the web interface. You could try editing the password file directly (Arduino or PIO file system upload, or http://rdzsonde.local/edit.html?file=networks.txt)

**Comment by JDat** [comment]
No, I am using only Latin alphabet and numbers. Just turned on, got latest update. Looks like everything working. We can close issue.

**Comment by dl9rdz** [comment]
Closing this issue. The other problem with not properly quoting " chars in the password (in the web interface) has also been fixed now.
