### ISSUE TITLE
Non Broadcasting Wifi

### ISSUE THREAD

**Issue by skysho** [dl9rdz/rdz_ttgo_sonde#395]
I recently changed my wifi to no longer broadcast and two of our RDZ's failed to connect.  I went in and made sure the information was accurate and even deleted and re-added the SSID and PW.  Still no luck, had to turn back on the broadcasting.  Two of my RPi running auto_rx and the other Radiosondy both dropped off but one of them had the ability to connect to a non broadcasting wifi.  So it worked fine, the Sondehub RPi didn't give me a choice so I cabled it to my switch.  Thanks for any suggestions.

**Comment by hr-ru** [comment]
What WiFi mode are you using?

**Comment by hr-ru** [comment]
In any case, I just checked, it will not work with hidden APs, as the software always uses WiFi scan (and this will not find non-broadcasting APs).  It would be possible to change to code such that it works with hidden APs, but this is currently not implemented.

**Comment by skysho** [comment]
Thanks for the info, I'll quit trying to find a work around.

**Comment by skysho** [comment]
Sorry, its just an Xfinity router so I’m not quite sure about the mode.


Sent from Mail for Windows

**Comment by dl9rdz** [comment]
Today's devel version adds a new WiFi mode 4. 

This mode directly connects to the second network in the config (i.e., # 1 in the web interface, below the AP name). It does not scan, so it works also with hidden SSIDs.

Note that in this mode you cannot configure multiple other networks.

Another change: In mode 1, 3 and 4, during the initial network scan, you can press any button of your board to change to AP mode temporarily (until reboot or rescan).
