### ISSUE TITLE
Livemap location reporting

### ISSUE THREAD

**Issue by 14ri004** [dl9rdz/rdz_ttgo_sonde#418]
Hello, I use a T-Beam in the car, and I would like to be able to have my blue dot move on LIVEMAP following my GPS position, but it does not work, the point is not visible on the map.
on the line: SondeHub location reporting (0=off, 1=fixed, 2=chase/GPS, 3=auto) 

--->  I put (2) = Chase/GPS

I'm talking about LIVEMAP, and not SondeHub

<img width="916" alt="Capture2" src="https://github.com/dl9rdz/rdz_ttgo_sonde/assets/87615097/8742808e-587e-4136-8ddc-b99eb8d83ba8">
<img width="916" alt="Capture3" src="https://github.com/dl9rdz/rdz_ttgo_sonde/assets/87615097/ff6b9400-6246-4ead-ad8c-caabd1ff7bbd">
<img width="895" alt="Capture1" src="https://github.com/dl9rdz/rdz_ttgo_sonde/assets/87615097/66f0861e-c685-4215-8fc6-7e270d966c4e">

I just added fixed coordinates, now I have the blue point displayed on LIVEMAP, but it does not move depending on my position, the position only changes each time the T-BEAM reboots, but not live

<img width="912" alt="Capture5" src="https://github.com/dl9rdz/rdz_ttgo_sonde/assets/87615097/49b726b4-480c-4d6c-b3eb-2a1e95c16a49">

<img width="687" alt="Capture4" src="https://github.com/dl9rdz/rdz_ttgo_sonde/assets/87615097/972b4298-569d-428e-96c0-45c2215038d9">

**Comment by 14ri004** [comment]
if I move on a mobile and find myself 20 km from the probe, LIVEMAP always positions me at the GPS coordinates indicated in the T-BEAM, which is not very precise for searching for the probe, since the T- BEAM uses a GPS chip, the position on LIVEMAP should be able to be indicated live as for the probe, is this function possible?, thank you

**Comment by LoickFahl** [comment]
I can confirm, upated my T Beam 1.2 from master_v0.9.2-B16 to master_v0.9.4-B17. I lost the livemap positioning (Dev or master)

**Comment by dl9rdz** [comment]
I think I understand, I am away from my testing equipment until next week though.

Maybe devel20230110 fixes the problem (completely untested, so no guarantees, but feel free to test)

**Comment by LoickFahl** [comment]
Just updated to devel20230110 , so far so good. I can see my position on the map.

master_v0.9.2-B16 -> devel20230110 : Livemap no user gps position fixed.
