### ISSUE TITLE
RDZTTGO APRS Reporting Issue

### ISSUE THREAD

**Issue by obi7zik** [dl9rdz/rdz_ttgo_sonde#435]
I've noticed a problem with the RDZTTGO APRS reporting. Even after selecting option 0 to disable location reporting, data continues to be transmitted. Could you look into this. ( firmware version devel20240316-B17) device ttgo T-Beam.

**Comment by 73-de-LZ** [comment]
Checked, when APRS location reporting=0 ,save then reboot devel20240316-B17 working as expected.

**Comment by obi7zik** [comment]
> Checked, when APRS location reporting=0, save then reboot devel20240316-B17 is working as expected.

Despite several attempts, I couldn't achieve success. Although option 1, which entails reporting a fixed location, is functional, I'm utilizing a T-Beam 1.1 board with a neo M8 module, and my preference is to have no location reported at all.

**Comment by hr-ru** [comment]
Yes I think there is something I need to fix. 
Currently my Travis CI plan for automated builds has expired, so I first need to get that part running again :)

**Comment by 73-de-LZ** [comment]
APRS and sondehub locations are different things, just to be sure we are at the same wavelenght?

**Comment by obi7zik** [comment]
> APRS and sondehub locations are different things, just to be sure we are at the same wavelenght?

The location reporting of SondeHub is functioning as expected without any issues, while APRS report the exact GPS location on radiosondy.info with the "0" option selected.

**Comment by dl9rdz** [comment]
Thanks for reporting this issue, this has been fixed now (in the latest commit).
Will be in the new IDF branch in the next dev version [note: no OTA available from old to new IDF)
