### ISSUE TITLE
GPS is not working after FW installed

### ISSUE THREAD

**Issue by mmadela** [dl9rdz/rdz_ttgo_sonde#44]
if it happens that the GPS is not sending any data however its LED flashes every 1s, here is a way to get T-Beam working:

compile, upload and run once
https://github.com/Xinyuan-LilyGO/LilyGO-T-Beam/tree/master/examples/GPS/Example3_FactoryDefaultsviaSerial
then install the rdz_ttgo_sonde firmware again

the reason is a firmware being flashed at factory, GPS coordinates are displayed properly by this FW, but it apparently disables continuous sending of GPS data,
the rdz_ttgo_sonde does not send anything to GPS and does not alter existing GPS configuration

**Comment by loefstrand** [comment]
The solution worked for me.

**Comment by dl9rdz** [comment]
From what I can see, the linked code basically does a factory reset of the GPS chip. I have never heard any comments regarding GPS not working directly, but it would not be difficult to add such functionality to my software. Its just probing multiple baud rate in case the GPS is not on the default 9600 and sending the reset command....

**Comment by smarti2019** [comment]
The GPS problem always came up when you had installed meshtastic, for example. Afterwards, GPS only works again after running the gps reset program.

**Comment by loefstrand** [comment]
I had also tested meshtastic on my unit and after that the GPS didn't want to work until reseting it..

**Comment by dl9rdz** [comment]
Ok, minor addition: If you configure the GPS TX pin (12 for the T-Beam 1.0). the software will send a "restore factory defaults" command to the GPS.  This should fix most configurations of the GPS chip done by other software.

Note that this will have effect only after you restart the GPS (i.e., power-cycle the T-Beam, pressing the reset button is not enough).
