### ISSUE TITLE
sending M10 data does not work either

### ISSUE THREAD

**Issue by 14ri004** [dl9rdz/rdz_ttgo_sonde#459]
Hello, for information, this morning I decoded a M10 901-2-11018 well, but invisible on sondehub, I started the SDR and the probe appeared well on Sondehub, sending data like the DFM17 does not work either with the M10

**Comment by dl9rdz** [comment]
version number?

If the devXX, any sondehub status information on the web interface?

**Comment by 14ri004** [comment]
rdzTTGOsonde version dev20240905

**Comment by dl9rdz** [comment]
What is on the status info? Any error message?

<img width="813" alt="Screenshot 2024-09-06 at 08 53 42" src="https://github.com/user-attachments/assets/dd589128-b7d4-4450-9d22-259038600a12">

**Comment by 14ri004** [comment]
I just tested on the M10 210-2-12462, the decoding and data are sent well with this probe, and this morning on another M10 nothing is displayed on sondehub, I don't understand why, so some probes must be blocked or locked??
