### ISSUE TITLE
save parameter

### ISSUE THREAD

**Issue by Braccato** [dl9rdz/rdz_ttgo_sonde#472]
Hi, with the new firmware 20241002 is it possible to save the parameter configuration?

**Comment by dl9rdz** [comment]
Yes it should be

**Comment by Braccato** [comment]
is there a guide?

**Comment by dl9rdz** [comment]
What exactly do you want to achieve? Can you explain in more detail?

**Comment by Braccato** [comment]
I wanted to save all the entered parameters to a file

**Comment by dl9rdz** [comment]
Ah ok I see... 

You can do so on the command line with a python script in the repository. Something like (for saving, and for re-uploading to the ttgo)
`python scripts/ttgoconfig.py --ttgo=192.168.1.9 get config`
`python scripts/ttgoconfig.py --ttgo=192.168.1.9 put config`

You can also do the "save to file" simply with the web browser by accessing
http://(ip-of-ttgo)/file/config.txt
But uploading via the web browser is only via http://(ip-of-ttgo)/edit.html?file=config.txt and then copy/paste the saved file into it.

**Comment by Braccato** [comment]
Grazie
