### ISSUE TITLE
Chasemaper data feed

### ISSUE THREAD

**Issue by 5B4APV** [dl9rdz/rdz_ttgo_sonde#66]
I was wondering if its possible to feed data to a device running chasemaper via Payload Summary UDP messages or any other method.

**Comment by LukePrior** [comment]
While not chasemapper you can now upload to SondeHub

**Comment by MCmakerPro** [comment]
Hello, thanks for the update. I have been following the sondehub pull request for a while now. Thanks for the contribution!

**Comment by darksidelemm** [comment]
I need to look into the UDP packets that are sent via this software... it may be possible to make chasemapper support them.

**Comment by darksidelemm** [comment]
Sorry to barge into a thread, but @5B4APV  could you possibly email me at vk5qi (at) rfhead.net ? I have some questions about your auto_rx configuration.

**Comment by fkemps** [comment]
I tried the UDP feed from latest rdz_ttgo_sonde (devel20210811-B14-full.bin) into Chasemapper, not been recognized yet.
This would be a welcome integration and looking forward to it.

Happy to give it a test run.

**Comment by darksidelemm** [comment]
The AXUDP feed is a different to format than what Chasemapper supports, but it's probably going to be easier to just add support for AXUDP into chasemapper than adding the chasemapper format into this repo. Unsure when I'll get to it though.

**Comment by darksidelemm** [comment]
Looking more into this, the AXUDP feed is not what I thought it was (some kind of verbose-ish format, instead it's APRS packets :-/ ). I don't really want to have to deal with APRS or KISS decoding in chasemapper.

The JSON format that is uploaded to Sondehub is 90% of the way to what chasemapper accepts as input via UDP, so maybe that's a way forward...

**Comment by dl9rdz** [comment]
Ok, no problem, not a big deal to put some json structure into a UDP message.  Should be in most recent devel today. Just lightly tested, so don't expect it to be complete or bug-free, but its a starting point....

**Comment by dl9rdz** [comment]
Ok, the real reason for that was slightly different to what I initially expected. Actually the sondehub network code was waiting for a newline character at the end of the response that sondehub did not send, so we blocked the main loop thread for a second (the default network timeout). This is why the decoder had already overwritten the old data with the new data, which we then sent twice.
Should be fixed now.

**Comment by dl9rdz** [comment]
OK, this is working nicely, so let's close the issue.
