### ISSUE TITLE
Map not showing in web UI

### ISSUE THREAD

**Issue by LukePrior** [dl9rdz/rdz_ttgo_sonde#73]
When I got to SondeMap on the WebUI I see the following:

![image](https://user-images.githubusercontent.com/22492406/113236602-e6633600-92f0-11eb-8f69-98dc0439a3ee.png)

How is this supposed to work?

Thanks

**Comment by Mooni123** [comment]
Sondemap Link/Site is no longer available and link is already removed in actual dev version of rdz_ttgo-sonde.

**Comment by DL2MF** [comment]
The link to my old website wx.dl2mf.de  is outdated since more than 1 year. 
I'm currently working on a fixed version in my fork and will contribute a PR soon.

**Comment by LukePrior** [comment]
> The link to my old website wx.dl2mf.de is outdated since more than 1 year.
> I'm currently working on a fixed version in my fork and will contribute a PR soon.

Exciting looking forward to it.

**Comment by LukePrior** [comment]
> I'm currently working on a fixed version in my fork and will contribute a PR soon.

Any progress on this?
