### ISSUE TITLE
webgo needs login

### ISSUE THREAD

**Issue by megabyte2010** [dl9rdz/rdz_ttgo_sonde#77]
Sonde map ask for login.

**Comment by dl9rdz** [comment]
Are you referring to the master version? The link to wx.dl2mf.de is no longer valid and is not present any more in the devel version for some time. Will be reflected in the next master version as well.

Also the wetterson.de link is no longer valid, will be removed in the next devel version.

So, for now, you have to use the radiosondy link (or for just your received sonde, the osm or google link or the app)

**Comment by dl9rdz** [comment]
no longer valid links are now removed in the devel version, instead sondehub link is added in addition to radiosondy
