### ISSUE TITLE
Overlapping text

### ISSUE THREAD

**Issue by rmoravcik** [dl9rdz/rdz_ttgo_sonde#78]
Hello,

today I upgraded to version devel20210524 and I observing text overlapping. Please, see the screenshot. I'm using TFT2" display with new alternative ALT9225 driver and screen3.txt.

![IMG_20210524_131629](https://user-images.githubusercontent.com/2954118/119343977-66759e80-bc97-11eb-98bc-bf4f0ca3d8fa.jpg)

**Comment by dl9rdz** [comment]
Thanks for testing. 

I have updated the font to use less space, please try if this solves the problem already. 

You could also rearrange the lines in screens3.txt such that the display is drawn from top to bottom, then this overlap should not be a problem as well.

(I did not update the version number, update is in devel20210524)

**Comment by rmoravcik** [comment]
Hello Hansi,

I just tested the latest version and it's working fine to me now. Thank you
