### ISSUE TITLE
M10 sonde [enhancement]

### ISSUE THREAD

**Issue by b4sh** [dl9rdz/rdz_ttgo_sonde#9]
Is it possible to add M10 sonde to decoder? If needed i can send working M10 sonde to author.

**Comment by dl9rdz** [comment]
I don't see any M10 in my location (the closest launch site with M10, Vienna, is >300km away), but if I get a working M10 and have some spare time available, I can give it a try. No promise :-) My address: Hansi Reiser, DL9RDZ, Stephanstr. 151, 94034 Passau, Germany.

It should be possible to receive M10 with the TTGO LORA, as F5ZJ seems to have a working implementation. Unfortunately I am unable to contact him (contact form on his site http://keraman.free.fr/ is dysfunctional, and I did not find any other way to contact him).

**Comment by sp3rat** [comment]
Hello  :)
It is e-mail to F5ZJ  kera5@free.fr
Jurek

**Comment by b4sh** [comment]
It turned out that my M10 sonde is damaged. When I hunt a new one, I will prepare a package.

**Comment by oe3jtb** [comment]
Hi Hansi, still open your M10 request? If yes , you have friends at Schärding or other near OE town? 73 Alex, OE3JTB

**Comment by oe6pwe** [comment]
Hello,
Contact me I can send you a M10.
73 Wolfgang, OE6PWE

**Comment by ok2it** [comment]
mee too , let me know if needed.

**Comment by dl9rdz** [comment]
Thanks to Wolfgang for sending me two M10 👍 

I will see what I can do.... might take a few weeks though as I am about to leave for holidays beginning of August, and then in September I am organizing the next HAMNET meeting in Passau (and a few other things...)

**Comment by dl9rdz** [comment]
I have added some code for M10 in devel20191101. Not much tested, but it decodes the two M10s I got :-)
Unlike the french software, it does not require wiring SX127x's DIO2 to an ESP32 GPIO pin, but instead attempts to use the FIFO, even if the modulation/frame format is not a good match to the RF chip's features... Not sure how reliable this works with weak signals though.
IDs are dxl new style.

**Comment by oe3jtb** [comment]
Hansi tnx for implementing M10, OE8JPQ and myself did a first test very fine thank you!!!

**Comment by dl9rdz** [comment]
Seems to work fine, so closing this issue :-)
