### ISSUE TITLE
Last line in qrg.txt can´t be configured.

### ISSUE THREAD

**Issue by beliffm** [dl9rdz/rdz_ttgo_sonde#93]
If the MAXSONDE parameter is set to n, only n-1 sondes can be configured. The last line always stays with 400.000 MHz regardless of any attempt to change it.

73s Bernd, DL1ZP

**Comment by beliffm** [comment]
Just wondering. Did I step on someones foot?

**Comment by dl9rdz** [comment]
No, thanks for the report.

"Its not a bug, it is just an unimplemented feature".  One entry was (long time ago) intended to be an entry to be changed dynamically (scanning, or some key presses to go up/down, or to copy peak from scanner, etc.). Has never been implemented, and is not intuitive, so I guess I should change it in the future.

**Comment by beliffm** [comment]
Thanks for the update, i appreciate it.

**Comment by dl9rdz** [comment]
In the latest version, this should be fixed now.
