### ISSUE TITLE
upload to Radiosondy and SondeHub does not work

### ISSUE THREAD

**Issue by hem0773** [dl9rdz/rdz_ttgo_sonde#98]
upload to Radiosondy and SondeHub does not work

Radiosondy here I entered the data from the account
Complete all fields at SondeHub

Do I need a GPS FIX?

**Comment by LukePrior** [comment]
> upload to Radiosondy and SondeHub does not work
> 
> Radiosondy here I entered the data from the account
> Complete all fields at SondeHub
> 
> Do I need a GPS FIX?

Can you send a picture of your SondeHub configuration settings?

**Comment by hem0773** [comment]
> 
> 
> > upload to Radiosondy and SondeHub does not work
> > Radiosondy here I entered the data from the account
> > Complete all fields at SondeHub
> > Do I need a GPS FIX?
> 
> Can you send a picture of your SondeHub configuration settings?

**Comment by hem0773** [comment]
> 
> 
> > upload to Radiosondy and SondeHub does not work
> > Radiosondy here I entered the data from the account
> > Complete all fields at SondeHub
> > Do I need a GPS FIX?
> 
> Can you send a picture of your SondeHub configuration settings?
![grafik](https://user-images.githubusercontent.com/57199067/125276782-e5d73400-e310-11eb-9afb-0904302630a3.png)

**Comment by LukePrior** [comment]
> > > upload to Radiosondy and SondeHub does not work
> > > Radiosondy here I entered the data from the account
> > > Complete all fields at SondeHub
> > > Do I need a GPS FIX?
> > 
> > 
> > Can you send a picture of your SondeHub configuration settings?
> > ![grafik](https://user-images.githubusercontent.com/57199067/125276782-e5d73400-e310-11eb-9afb-0904302630a3.png)

Set chase location active to 0 (you have it enabled so it is searching for hardware GPS which it cannot find).
You should also set the antenna field to a string such as "dipole antenna"

**Comment by hem0773** [comment]
> 
> 
> > > > upload to Radiosondy and SondeHub does not work
> > > > Radiosondy here I entered the data from the account
> > > > Complete all fields at SondeHub
> > > > Do I need a GPS FIX?
> > > 
> > > 
> > > Can you send a picture of your SondeHub configuration settings?
> > > ![grafik](https://user-images.githubusercontent.com/57199067/125276782-e5d73400-e310-11eb-9afb-0904302630a3.png)
> 
> Set chase location active to 0 (you have it enabled so it is searching for hardware GPS which it cannot find).
> You should also set the antenna field to a string such as "dipole antenna"

sondehub.org

**Comment by hem0773** [comment]
> 
> 
> > > > upload to Radiosondy and SondeHub does not work
> > > > Radiosondy here I entered the data from the account
> > > > Complete all fields at SondeHub
> > > > Do I need a GPS FIX?
> > > 
> > > 
> > > Can you send a picture of your SondeHub configuration settings?
> > > ![grafik](https://user-images.githubusercontent.com/57199067/125276782-e5d73400-e310-11eb-9afb-0904302630a3.png)
> 
> Set chase location active to 0 (you have it enabled so it is searching for hardware GPS which it cannot find).
> You should also set the antenna field to a string such as "dipole antenna"

made the changes!

No success, nothing is displayed on sondehub.org

**Comment by hem0773** [comment]
![grafik](https://user-images.githubusercontent.com/57199067/125329539-e63df200-e345-11eb-9a63-e6213abf89b9.png)
THX

**Comment by Jan-NiklasB** [comment]
@LukePrior 
So it I understand the posts Herr right, the chasemode isn't functional AG the Moment, right?

It thats the Gase, it would be cool if the TTGO would report it's position when opening sondehub in the web UI.

Greetings
Jan-Niklas

**Comment by LukePrior** [comment]
> So if I understand the posts here right, the chasemode isn't functional at the Moment, right?

Chase mode works if you have a GPS connected to the TTGO device

**Comment by Jan-NiklasB** [comment]
Well, I have a T-beam including a Neo6m.
But it I try to set it up and open Sondehub over the UI I get a json response with forbidden. 

If you want me to, I can open a separate issue for this.

**Comment by LukePrior** [comment]
> Well, I have a T-beam including a Neo6m.
> But it I try to set it up and open Sondehub over the UI I get a json response with forbidden.
> 
> If you want me to, I can open a separate issue for this.

Yeah I'm not entirely sure about that might be a good idea to open a new issue and post all the details.

**Comment by Jan-NiklasB** [comment]
I can send you my config in this thread tomorrow, maybe you can tell me directly where my issue comes from or that I should open a new issue.
